### ISSUE TITLE
Warning about permissible value lengths even though their length is less than 255 characters

### ISSUE THREAD

**Issue by turbomam** [kaiiam/mifc#13]
From `make all`

For example:

> WARNING:linkml.generators.excelgen:'FoodCookingMethod' has permissible values with total length > 255 characters. Dropdowns may not work properly in /home/mark/gitrepos/mifc/project/excel/mifc.xlsx

We should characterize this some more and possibly raise an issue in linkml/linkml

**Comment by kaiiam** [comment]
Comes up sometimes for me as well when I run `make all-all`, but not every time I run it.

**Comment by turbomam** [comment]
Hah, the total character size of `FoodCookingMethod`'s permissible value names is 330. So the warning is valid and the underlying problem is a constraint from Excel. I think we just have to live with this.

**Comment by kaiiam** [comment]
OK cool thanks @turbomam if it's just an excel issue then ya we'll have to live with it. Hopefully the enum values will work in excel. On a related note I'm thinking of for example having all iso3 country codes in a new enum, I hope something like that also works in the excel version. TBD. I guess we close for now if this isn't something we can fix. Thanks again Mark.
