### ISSUE TITLE
documentation doesn't seem to be up-to-date

### ISSUE THREAD

**Issue by turbomam** [kaiiam/mifc#18]
Ask Sujay Patil for help

- doesn't include table sorting widgets
- maybe more

"not up to date" may mean missing Jinja template, old GH actions or something else

**Comment by kaiiam** [comment]
Thanks @turbomam for raising this. Sometimes the docs are slow to deploy but good to figure out if something non standard has been happening.

**Comment by turbomam** [comment]
cc @sujaypatil96

**Comment by turbomam** [comment]
to discuss with LinkML community: how to keep the documentation generation features up to date? 

@sujaypatil96 and I are inclined to say `cruft update` but Patrick Kalita discourages that

If we can get `cruft update`  to work in an addition only mode, it would bring in many other features besides just doc gen
