### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by kaiiam** [kaiiam/mifc#31]
Easy fix in the README file for the project

`gets an issue number e.g. issue https://github.com/kaiiam/mifc/issues/28` the G should be capitalized, or you can make the sentence better. Great first issue for @ahasanzadeh13.

**Comment by ahasanzadeh13** [comment]
The issue has been solved. The letter 'g' is now uppercase.

**Comment by kaiiam** [comment]
Ok great thanks @ahasanzadeh13. Next time we'll try it with a Pull Request 😂 glad you were able to get it done at least via commits to the main branch.
